server:
  port: 8090

spring:
  application:
    name: CloverSparkService

spark:
  master: local[*]
  localhost: 127.0.0.1
  port: 8090
  appName: CloverSparkService
  checkpoint: checkpoint
  httpEntityName: Entity
  statusCodeName: StatusCode
  driver:
    memory: 32g
    name: spark.driver.memory
  worker:
    memory: 25g
    name: spark.worker.memory
  executor:
    memory: 25g
    name: spark.executor.memory
  rpc:
    message:
      name : spark.rpc.message.maxSize
      maxSize: 1024
  kafka:
    topics: product
    stream:
      durations: 2
    broker:
      name: metadata.broker.list
      list : localhost:9092
  cassandra:
    host: spark.cassandra.connection.host
    streamInsertURI: http://localhost:8091/api/v1/product/create
    durations: 2
    keyspace: PRODUCT_DB_TEST
    table: PRODUCT_TBL_TEST
  constants:
    timeouts:
      connectionTimeout: 30000
      connectionRequestTimeout: 30000
      socketTimeout: 60000
      defaultKeepAliveTime: 20000
      completableFutureTimeoutValue: 10000
    connectionPool:
      maxRouteConnections: 40
      maxTotalConnections: 40
      maxLocalHostConnections: 80
    executor:
      threadNamePrefix: Async-Clover-


